# Generated by Django 5.2.7 on 2025-10-26 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nit', models.CharField(max_length=20)),
                ('nrc', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nrc', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('actividad_economica', models.CharField(blank=True, max_length=150, null=True)),
                ('representante_legal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('unidad_medida', models.CharField(default='C/U', max_length=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dte', models.CharField(choices=[('01', 'Factura'), ('03', 'Comprobante de Crédito Fiscal'), ('05', 'Nota de Crédito'), ('06', 'Nota de Débito')], default='03', max_length=2)),
                ('numero_control', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('condicion_pago', models.CharField(default='Contado', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo_generacion', models.CharField(blank=True, max_length=100, null=True)),
                ('sello_recepcion', models.CharField(blank=True, max_length=150, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Facturacion.dte')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.producto')),
            ],
        ),
    ]
