# Generated by Django 5.2.7 on 2025-10-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nrc', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dte',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Anulado', 'Anulado')], default='Activo', max_length=10),
        ),
    ]
