# Generated by Django 5.2.7 on 2025-11-03 03:28

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0005_producto_inventario_alter_inventario_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comprobante_numero', models.CharField(max_length=50)),
                ('registro_nrc', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=150)),
                ('compras_gravadas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('iva_13', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
