# Generated by Django 5.2.7 on 2025-11-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0006_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='inventario',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
