# Generated by Django 5.2.7 on 2025-11-06 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0007_alter_producto_inventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dte',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalledte',
            name='total_item',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dte',
            name='tipo_dte',
            field=models.CharField(choices=[('01', 'Factura'), ('03', 'Comprobante de Crédito Fiscal'), ('05', 'Nota de Crédito'), ('06', 'Nota de Débito'), ('07', 'Retención'), ('11', 'Liquidación')], default='01', max_length=2),
        ),
    ]
