# Generated by Django 5.2.7 on 2025-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0009_cliente_empresa_compra_empresa_perfil_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dui',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
