# Generated by Django 5.2.7 on 2025-11-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0010_cliente_dui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
