# Generated by Django 5.2.7 on 2025-11-13 19:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0011_alter_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
